### PR TITLE
removed unused, hacky TM settings

### PR DESCRIPTION
**Pull request by dan12321**
This is to get USB printing working for QL-810W and QL-800. I thought this was working with QL-820NWB but changing to QL-810W I'm currently getting ERROR_INTERNAL_ERROR from the printer

### CODE REVIEW

**Comment by dan12321** [comment]
Haven't found anything useful on ERROR_INTERNAL_ERROR, the description is just "internal error" with no further documentation. The full list of possible errors is here https://support.brother.co.jp/j/s/support/html/mobilesdk/reference/android/printerinfo.html#errorcode which can be used to help determine what the error is not.

Using the SDK demo app and the configure.prn file produced by our app I confirmed the print instructions work when sent to the printer correctly. I also believe that before these changes this code worked with the QL-820NWB so maybe something has gone wrong when refactoring (or working version might no longer exist since the original purpose was abandoned)

**Comment by dan12321** [comment]
I noticed the documentation for printFile says it takes a file path but providing a path used to make the file doesn't fix the issue.

**Comment by dan12321** [comment]
I tried using without these changes (small edits to not require the bin file for TM) and had the same error even before correcting the QL model so I think it's running into an issue before it even check the printer because otherwise I would have expected `ERROR_NOT_SAME_MODEL` for the TD_2120N and QL_220NWB print attempts.

At this point I'm considering updating the SDK version and using PrintDriver but that has even less examples and the documentation isn't great so that would take a while and might run into the same problem. But while there aren't as good examples the error handling looks better (see [PrintError](https://support.brother.com/g/s/es/htmldoc/mobilesdk/reference/android_v4/printerror.html) and [ValidatePrintSettings](https://support.brother.com/g/s/es/htmldoc/mobilesdk/reference/android_v4/validateprintsettings.html)) which will make it easier to debug

I think the reference linked above contains links to examples but in Japanese, here it is for english https://support.brother.com/g/s/es/htmldoc/mobilesdk/guide/print-image.html

**Comment by dan12321** [comment]
I've fixed it not printing by updating the jar to the latest. The latest v4 SDK includes the v3 SDK so no code changes are needed other than those to support QL-810W and QL-800. The actual SDK uses an .aar file but from what we have it was faster and easier to just take the jar file from it.

The v4 looks like it has nicer error handling which would be easier to work with it wouldn't be a fast refactor. On top of this it sounds like they intend to remove support for the v3 SDK  classes and encourage people to switch but I haven't seen a hard deadline for it https://support.brother.com/g/s/es/dev/en/mobilesdk/download/index.html?c=eu_ot&lang=en&navi=offall&comple=on&redirect=on#android.

For now I won't worry the v4 SDK migration but this will be required at some point

**Comment by dan12321** [comment]
I've made changes to allow different printer models. Currently the QL-800 power button is flashing red when I try to print (Brother SDK Demo as well as our app). This could just be an issue for me but I haven't trouble shooted yet.

It matches "1 time for 2 seconds" (found by comparing with QL-810W when I open cassette mid print)
Screenshot 2021-08-23 at 15 39 07

**Comment by dan12321** [comment]
The Files changed looks off to me but I'm not sure what the merge issue is. The changes I made are to BrotherPrinter.java, replace BrotherPrinterLibrary.jar and two small corrections to their BasePrinter class to stop build errors

**Comment by dan12321** [comment]
I still get the errors mentioned for QL-800 but it's more important that clients can print with something for now

**Comment by dan12321** [comment]
I've rearranged things to use the aar file. It still crashes on release builds

**Comment by dan12321** [comment]
Fixed the crashes on the app side https://github.com/dynamifylimited/dynamify-merchant/pull/90

**Review by nhuang0313 — APPROVED** [review]

**Pull request merged**
